# SPDX-FileCopyrightText: 2025 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only
---
updates:
  - directories:
      - misp-ha-proxy/
      - misp-modules/
      - misp-shibb-sp/
      - misp-web/
      - misp-workers/
    package-ecosystem: docker
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: docker-compose
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2