---
updates:
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: docker-compose
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2