# SPDX-FileCopyrightText: 2023 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

version: '3'
name: misp
services:
  clamav:
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
    hostname: ${CLAMAV_HOSTNAME:-misp_clamav}
    image: clamav/clamav:1.0_base
    restart: unless-stopped
    volumes:
      - ./persistent/${COMPOSE_PROJECT_NAME}/clamav_db/:/var/lib/clamav
  db:
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all]
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - MYSQL_DATABASE=${MYSQL_DBNAME:-misp}
      - MYSQL_USER=${MYSQL_USERNAME:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misp}
    hostname: ${MYSQL_HOSTNAME:-misp_db}
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - ./persistent/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql
  modules:
    depends_on:
      clamav:
        condition: service_healthy
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - WORKERS_PASSWORD=${WORKERS_PASSWORD:-misp}
    hostname: ${MODULES_HOSTNAME:-misp_modules}
    image: jisccti/misp-modules:latest
    restart: unless-stopped
  redis:
    entrypoint: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD:-misp}
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - REDISCLI_AUTH=${REDIS_PASSWORD:-misp}
    healthcheck:
      test: redis-cli -e ping || exit 1
    hostname: ${REDIS_HOST:-misp_redis}
    image: redis:7
    restart: unless-stopped
  web:
    depends_on:
      db:
        condition: service_healthy
      modules:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CLAMAV_HOSTNAME=${CLAMAV_HOSTNAME:-misp_clamav}
      - FQDN=${FQDN:-misp.local}
      - GPG_PASSPHRASE=${GPG_PASSPHRASE:-misp}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - MISP_EMAIL_ADDRESS=${MISP_EMAIL_ADDRESS:-misp@misp.local}
      - MISP_EMAIL_NAME=${MISP_EMAIL_NAME:-MISP}
      - MODULES_HOSTNAME=${MODULES_HOSTNAME:-misp_modules}
      - MYSQL_DBNAME=${MYSQL_DBNAME:-misp}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME:-misp_db}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-misp}
      - ORG_NAME=${ORG_NAME:-ORGNAME}
      - REDIS_HOST=${REDIS_HOST:-misp_redis}
      - REDIS_MISP_DB=${REDIS_MISP_DB:-2}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-misp}
      - REDIS_WORKER_DB=${REDIS_MISP_DB:-3}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME:-localhost}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-misp}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_STARTTLS=${SMTP_STARTTLS:-true}
      - SMTP_USERNAME=${SMTP_USERNAME:-misp}
      - WORKERS_HOSTNAME=${WORKERS_HOSTNAME:-misp_workers}
      - WORKERS_PASSWORD=${WORKERS_PASSWORD:-misp}
    hostname: ${MISP_HOSTNAME:-misp_web}
    image: jisccti/misp-web:latest
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    restart: unless-stopped
    volumes:
      - ./persistent/${COMPOSE_PROJECT_NAME}/data/:/var/www/MISPData
      - ./persistent/${COMPOSE_PROJECT_NAME}/gpg/:/var/www/MISPGnuPG
      - ./persistent/${COMPOSE_PROJECT_NAME}/tls/:/etc/ssl/private
  workers:
    depends_on:
      web:
        condition: service_started
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - ORG_NAME=${ORG_NAME:-ORGNAME}
      - REDIS_HOST=${REDIS_HOST:-misp_redis}
      - WORKERS_PASSWORD=${WORKERS_PASSWORD:-misp}
    hostname: ${WORKERS_HOSTNAME:-misp_workers}
    image: jisccti/misp-workers:latest
    restart: unless-stopped
    volumes:
      - ./persistent/${COMPOSE_PROJECT_NAME}/data/:/var/www/MISPData
