# SPDX-FileCopyrightText: 2023 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Test Deploy

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        uses: canastro/copy-file-action@master
        with:
            source: "example.env"
            target: ".env"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ vars.DOCKERHUB_USERNAME }}

      - name: Deploy and Test
        uses: cloudposse/github-action-docker-compose-test-run@main
        env:
          COMPOSE_PROJECT_NAME: misp-test
        with:
          file: docker-compose.yml
          registry: registry.hub.docker.com
          service: misp_web
          command: /github-test.sh
