# SPDX-FileCopyrightText: 2023 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Test Deploy

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
  workflow_dispatch:

env:
  COMPOSE_PROJECT_NAME: misp-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Configure Environment
        run: |
          cp example.env .env
          mkdir -p persistent/$COMPOSE_PROJECT_NAME/gpg persistent/$COMPOSE_PROJECT_NAME/tls
          cat <<EOF > persistent/$COMPOSE_PROJECT_NAME/gpg/import.asc
          ${{ secrets.TEST_PGP_KEY }}
          EOF
          cat <<EOF > persistent/$COMPOSE_PROJECT_NAME/tls/misp.crt
          ${{ secrets.TEST_TLS_CERT }}
          EOF
          cat <<EOF > persistent/$COMPOSE_PROJECT_NAME/tls/misp.key
          ${{ secrets.TEST_TLS_KEY }}
          EOF

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ vars.DOCKERHUB_USERNAME }}

      - name: Deploy MISP
        run: docker compose up -d

      - id: initial_setup
        name: Wait for Initial Setup
        run: timeout 10m /bin/bash -c 'while [[ $(docker container ls --format {{.Status}} | grep -P "(unhealthy)|(starting)" | wc -l) -gt 0 ]] ; do sleep 30; done'
        continue-on-error: true

      - name: Dump Container Log
        run: |
          docker compose logs
          exit 1
        if: steps.initial_setup.outcome == 'failure'

      - name: Stop MISP
        run: docker compose down
