# SPDX-FileCopyrightText: 2023 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Test Deploy

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        uses: canastro/copy-file-action@master
        with:
            source: "example.env"
            target: ".env"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ vars.DOCKERHUB_USERNAME }}

      - name: Deploy MISP
        env:
          COMPOSE_PROJECT_NAME: misp-test
        run: docker compose up --detach

      - name: Wait for Initial Setup
        run: timeout 30m /bin/bash -c "while [[ $(docker container ls | grep misp_web | grep '(healthy)' | wc -l) -eq 0 ]] ; do sleep 30; done"

      - name: Stop MISP
        env:
          COMPOSE_PROJECT_NAME: misp-test
        run: docker compose down
