# SPDX-FileCopyrightText: 2024-2025 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only
---
jobs:
  run:
    name: Update DockerHub Pages
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Project
        uses: actions/checkout@v4
      - id: modules
        name: MISP Modules
        uses: peter-evans/dockerhub-description@v4
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: docs/misp-modules.md
          repository: ${{ vars.DOCKERHUB_ORGANISATION }}/misp-modules
          short-description: MISP Modules for use with ${{ vars.DOCKERHUB_ORGANISATION }}/misp-web.
          username: ${{ vars.DOCKERHUB_USERNAME }}
      - id: web
        name: MISP Web
        uses: peter-evans/dockerhub-description@v4
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: docs/misp-web.md
          repository: ${{ vars.DOCKERHUB_ORGANISATION }}/misp-web
          short-description: MISP with self-configuration into a usable state from first start.
          username: ${{ vars.DOCKERHUB_USERNAME }}
      - id: workers
        name: MISP Workers
        uses: peter-evans/dockerhub-description@v4
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: docs/misp-modules.md
          repository: ${{ vars.DOCKERHUB_ORGANISATION }}/misp-workers
          short-description: MISP Simple Background Job Workers for use with ${{ vars.DOCKERHUB_ORGANISATION }}/misp-web.
          username: ${{ vars.DOCKERHUB_USERNAME }}
      - id: shibb
        name: MISP Shibboleth SP
        uses: peter-evans/dockerhub-description@v4
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: docs/misp-shibb-sp.md
          repository: ${{ vars.DOCKERHUB_ORGANISATION }}/misp-shibb-sp
          short-description: Shibboleth Service Provider for use with ${{ vars.DOCKERHUB_ORGANISATION }}/misp-web.
          username: ${{ vars.DOCKERHUB_USERNAME }}
name: Update DockerHub
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read